# Base image
FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

# Copy latest mise image
COPY --from=jdxcode/mise /usr/local/bin/mise /usr/local/bin/


#USER vscode
# make sure mise is activated in both zsh and bash. Might be overridden by a user's dotfiles.
RUN echo 'eval "$(mise activate bash)"' >> /home/vscode/.bashrc && \
    echo 'eval "$(mise activate zsh)"' >> /home/vscode/.zshrc
